#!/bin/bash
export EVOSTEER_HOME=${EVOSTEER_HOME:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}
export EVOSTEER_MODELS=${EVOSTEER_MODELS:-$EVOSTEER_HOME/models}
export EVOSTEER_DATA=${EVOSTEER_DATA:-$EVOSTEER_HOME/data}
export EVOSTEER_RUNS=${EVOSTEER_RUNS:-$EVOSTEER_HOME/runs}
export EVOSTEER_LOGS=${EVOSTEER_LOGS:-$EVOSTEER_HOME/logs}
export EVOSTEER_TRAIN_PY=${EVOSTEER_TRAIN_PY:-python}
export EVOSTEER_SGLANG_PY=${EVOSTEER_SGLANG_PY:-python}
export EVOSTEER_EXECUTOR_URL=${EVOSTEER_EXECUTOR_URL:-http://127.0.0.1:31000}
export EVOSTEER_RETRIEVAL_URL=${EVOSTEER_RETRIEVAL_URL:-http://127.0.0.1:18010}
export EVOSTEER_PYTHON_TOOL_ISOLATION=${EVOSTEER_PYTHON_TOOL_ISOLATION:-unshare-net}
export EVOSTEER_PYTHON_TOOL_FS=${EVOSTEER_PYTHON_TOOL_FS:-landlock}
export EVOSTEER_PYTHON_TOOL_CONCURRENCY=${EVOSTEER_PYTHON_TOOL_CONCURRENCY:-8}
export CUDA_DEVICE_ORDER=PCI_BUS_ID
export HF_HUB_OFFLINE=${HF_HUB_OFFLINE:-1} TRANSFORMERS_DISABLE_DEEPGEMM_LINEAR=1
export PYTORCH_CUDA_ALLOC_CONF=${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}
export NO_PROXY=127.0.0.1,localhost no_proxy=127.0.0.1,localhost
mkdir -p "$EVOSTEER_RUNS" "$EVOSTEER_LOGS"
free_mib() { nvidia-smi --query-gpu=index,uuid,memory.free --format=csv,noheader,nounits | awk -F', ' -v g="$1" '$1==g || $2==g {print $3}'; }
